remote_theme: pages-themes/minimal
title: Richard Yifan Zhou
header_image: /assets/profile.jpg
description: Queen Mary University of London
show_downloads: false

# 如果你有社交媒体账号，可以在这里添加（可选）
# github_username: yourusername
# linkedin_username: yourusername
